"use client";

import React, {useRef} from "react";
import style from "./home.module.scss";
import Image from "next/image";
import Link from "next/link";

function BrowseItem({
    imageAlt,
    imageSrc,
    caption,
    redirectTo
}: {
    imageSrc: string;
    imageAlt: string;
    caption: string;
    redirectTo: string;
}) {
    return (
        <figure
            className={style.browseItem}
            onClick={() => window.location.href = redirectTo}
        >
            <Image
                src={imageSrc} alt={imageAlt}
                width={300} height={300}
            />
            <figcaption>{caption}</figcaption>
        </figure>
    );
}

export default function Home() {
    const introductionRef = useRef<HTMLDivElement>(null);

    return (
        <>
            <section className={style.hero}>
                <div className="fadein">
                    <h1 className="text-4xl mb-4">Tișcă Cătălin</h1>
                    <h2 className="text-xl mb-8 border-b pb-8">intheloop</h2>
                    <div className={"flex flex-wrap gap-4"}>
                        <Link href={"/about"} className="btn">
                            about
                        </Link>
                        <Link href={"/contact"} className="btn">
                            contact
                        </Link>
                    </div>
                </div>
                <Image
                    src="/home/programmer.jpg" alt="programmer"
                    loading="lazy"
                    className="w-32 sm:w-64 rounded-lg shadow-slate-500 shadow-lg fadein"
                    width={400}
                    height={400}
                />

                <button
                    type="button"
                    className="absolute bottom-4 outline-none z-10 fadein"
                    onClick={() => {
                        introductionRef.current?.scrollIntoView({
                            behavior: "smooth"
                        });
                    }}
                >
                    <Image
                        src="/icons/down.svg"
                        alt="down"
                        className="invert w-32 h-16"
                        width={32}
                        height={16}
                    />
                </button>
            </section>
            <section
                ref={introductionRef}
                className={`${style.introduction} padding-container`}
            >
                <div className={"mb-4 sm:mb-0"}>
                    <h2 className="text-3xl md:text-5xl mb-4">who am I?</h2>

                    <p className="md:text-xl mb-8">
                        I am a high school student with an expertise within software engineering,
                        working in many fields such as web development, or system engineering for
                        the past 7 years. I would like to consider myself as someone with a passion
                        for creating. You can find more about myself by pressing the button below.
                    </p>

                    <Link
                        href={"/about"}
                        className={"btn"}
                    >find more</Link>
                </div>
                <figure className="w-full max-w-96 max-h-96 justify-self-center self-center ">
                    <Image
                        src="/home/thworldisyours.png"
                        alt="the world is yours"
                        className="min-w-32 rounded-lg shadow-slate-500 shadow-lg block mx-auto"
                        width={200}
                        height={200}
                    />
                    <figcaption className="text-center italic mt-4">
                        {`"the world is yours" artwork`},<br/>generated by DALL-E
                    </figcaption>
                </figure>
            </section>
            <section className={`${style.browse} padding-container`}>
                <h2 className="text-3xl text-center mb-4">browse</h2>

                <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 sm:px-4 pt-4 gap-8">
                    <BrowseItem
                        caption="about"
                        imageSrc="/home/browse/about.png"
                        imageAlt="about"
                        redirectTo="/about"
                    />

                    <BrowseItem
                        caption="contact"
                        imageSrc="/home/browse/contact.png"
                        imageAlt="contact"
                        redirectTo="/contact"
                    />

                    <BrowseItem
                        caption="projects"
                        imageSrc="/home/browse/projects.png"
                        imageAlt="projects"
                        redirectTo="/projects"
                    />

                    <BrowseItem
                        caption="resume"
                        imageSrc="/home/browse/cv.png"
                        imageAlt="resume"
                        redirectTo="/Resume.pdf"
                    />
                </div>
            </section>
        </>
    );
}
