name: update deployment
on: [push]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: executing remote ssh commands using password
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        port: ${{ secrets.PORT }}
        script: |
          cd ~/intheloop
          git pull origin main
          alias npm=/root/.nvm/versions/node/v20.12.2/bin/npm
          alias node=/root/.nvm/versions/node/v20.12.2/bin/node
          alias pm2=/root/.nvm/versions/node/v20.12.2/bin/pm2
          npm run build
          pm2 restart tiscacatalin.com
